authorName: Pt
experimentName: sfi_fim
trialConcurrency: 1
maxExecDuration: 
maxTrialNum: 
trainingServicePlatform: local
# 搜索空间文件
searchSpacePath: /home/peitian_zhang/Codes/News-Recommendation/configs/sfi_fim.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
# 运行的命令，以及 Trial 代码的路径
trial:
  command: python sfi_fim.py -m tune -s demo -e 1 --topk=30 --select=gating --nni
  codeDir: /home/peitian_zhang/Codes/News-Recommendation/scripts/tuning/